// <auto-generated />
using System;
using ControlePortaria.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ControlePortaria.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240621123601_CorrecaoTabela")]
    partial class CorrecaoTabela
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ControlePortaria.Models.Carro", b =>
                {
                    b.Property<int>("CarroID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarroID"));

                    b.Property<bool>("CarroDisponivel")
                        .HasColumnType("bit");

                    b.Property<string>("CarroModelo")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("CarroPlaca")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("Fabricante")
                        .HasColumnType("int");

                    b.Property<int>("Kilometragem")
                        .HasColumnType("int");

                    b.HasKey("CarroID");

                    b.ToTable("Carro");
                });

            modelBuilder.Entity("ControlePortaria.Models.Pessoa", b =>
                {
                    b.Property<int>("PessoaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PessoaId"));

                    b.Property<string>("PessoaNome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PessoaStatus")
                        .HasColumnType("int");

                    b.Property<string>("PessoaTelefone")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("PessoaId");

                    b.ToTable("Pessoa");
                });

            modelBuilder.Entity("ControlePortaria.Models.Portaria", b =>
                {
                    b.Property<int>("PortariaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PortariaID"));

                    b.Property<int>("CarroID")
                        .HasColumnType("int");

                    b.Property<string>("Destino")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<byte[]>("FotoKilometragem")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<DateTime>("HorarioChegada")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("HorarioSaida")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("KilometragemChegada")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PessoaID")
                        .HasColumnType("int");

                    b.HasKey("PortariaID");

                    b.HasIndex("CarroID");

                    b.HasIndex("PessoaID");

                    b.ToTable("Portaria");
                });

            modelBuilder.Entity("ControlePortaria.Models.Portaria", b =>
                {
                    b.HasOne("ControlePortaria.Models.Carro", "Carro")
                        .WithMany()
                        .HasForeignKey("CarroID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ControlePortaria.Models.Pessoa", "Pessoa")
                        .WithMany()
                        .HasForeignKey("PessoaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Carro");

                    b.Navigation("Pessoa");
                });
#pragma warning restore 612, 618
        }
    }
}
